### PR TITLE
Avoid obtaining Vertx from CDI

### PR DESCRIPTION
**Pull request by geoand**
This is needed because the VertxVaultClient can potentially be used inside a Synthetic bean and in such cases
obtaining Vertx which is itself a synthetic bean is not possible

Fixes: #78

### CODE REVIEW

**Comment by kdubb** [comment]
@geoand I'm not sure this does exactly what the previous code was doing. I need to look at this more in depth and report back.

The goal with Shared/Private is to ensure the system provided VertX (aka Shared) is used whenever it is available but for config related queries we _might_ need to create a temporary (aka Private) VertX instance to query Vault before the system provides one.

**Comment by kdubb** [comment]
I'm realizing that `createSharedVaultClient` is not the best name for this function. It should at least be `createSharedVaultClientIfAvailable`.

**Comment by geoand** [comment]
Right, that's also what my PR does, doesn't it?

**Comment by kdubb** [comment]
This is a `@Dependent` producer. Previously it was not always creating a new client but only used as a way to lookup the best available client (shared or private). Now it is creating a new client for each injection point.

**Comment by geoand** [comment]
Okay, so how would you like to handle it?

**Comment by kdubb** [comment]
I think the following works. Basically the same code just uses `VertxRecorder.getVerx()` as the flag for shared vs. private and then requests it directly in the constructor instead of injecting it.

```java
@Produces
@Dependent
public static VertxVaultClient createSharedVaultClient() {
    Annotation clientType;
    if (VertxRecorder.getVertx() != null) {
        clientType = Shared.Literal.INSTANCE;
    } else {
        clientType = Private.Literal.INSTANCE;
    }
    return Arc.container().select(VertxVaultClient.class, clientType).get();
}
```

```java
public SharedVertxVaultClient(VaultConfigHolder vaultConfigHolder, TlsConfig tlsConfig) {
    super(vaultConfigHolder.getVaultBootstrapConfig().url.orElseThrow(() -> new VaultException("no vault url provided")),
            vaultConfigHolder.getVaultBootstrapConfig().enterprise.namespace,
            vaultConfigHolder.getVaultBootstrapConfig().readTimeout);
    Vertx vertx = Vertx.newInstance(VertxRecorder.getVertx());
    this.webClient.set(createHttpClient(vertx, vaultConfigHolder.getVaultBootstrapConfig(), tlsConfig));
}
```

**Comment by kdubb** [comment]
I tested this locally. I can push the changes to the PR branch.

**Comment by geoand** [comment]
Sounds good to me

**Pull request merged**
