### PR TITLE
Prepare for 3.2.0 release

### PR DESCRIPTION
**Pull request by vsevel**

### CODE REVIEW

**Comment by gsmet** [comment]
Let's not merge that for now, I restarted the job and it looks better.

**Comment by gsmet** [comment]
The release was successful in the other PR second run so I will close this.

**Comment by vsevel** [comment]
ok thanks @gsmet we have a  `3.2.0` tag
let me know if you need anything else

**Comment by gsmet** [comment]
It should be all good now. Thanks.

**Pull request closed without merging**
