### PR TITLE
VaultKvManager: Convert using String.valueOf

### PR DESCRIPTION
**Pull request by edelfour**
in private convert method use String.valueOf instead of String cast to convert value fetched from vault.

resolve quarkiverse/quarkus-vault#189

### CODE REVIEW

**Comment by edelfour** [comment]
Hello @gsmet 
I fixed the formatting error which failed the pipeline.

**Comment by gsmet** [comment]
@edelfour that being said, the tests are not passing AFAICS

**Comment by edelfour** [comment]
Hello @gsmet 
Thanks, I'm on it. I have run a just `mvn clean test` on my local environment instead of `./mvnw -B formatter:validate verify --file pom.xml -Dnative` in the pipeline configuration.
Sorry for the disturbance

**Comment by vsevel** [comment]
> @kdubb @vsevel any chance one of you could have a look? The change makes sense to me but I would prefer if one of you could check and approve it.

@gsmet yes. we have been discussing in the issue https://github.com/quarkiverse/quarkus-vault/issues/189

**Comment by edelfour** [comment]
a better solution was proposed by @vsevel in https://github.com/quarkiverse/quarkus-vault/issues/189  
I close the PR  
Thanks for your help :-)

**Pull request closed without merging**
