### PR TITLE
JDK 17

### PR DESCRIPTION
**Pull request by vsevel**

### CODE REVIEW

**Comment by kdubb** [comment]
@vsevel Isn't this already done in #238?

**Comment by vsevel** [comment]
> @vsevel Isn't this already done in #238?

yes @kdubb 
this PR was originally intending to move to CR1 then 3.8.0, plus JDK 17
the only thing to do is JDK 17
can you validate?
then I will do the release, and update the platform

**Comment by kdubb** [comment]
👍 All good for me

**Comment by kdubb** [comment]
@vsevel I think we can remove the compiler source/target versions altogether because they are set in the base Quarkivers POM; I noticed they are absent in my other Quarkiverse projects.

@gastaldi Can you confirm this?

**Pull request merged**
