### PR TITLE
Prepare release 4.1.0.CR2

### PR DESCRIPTION
**Pull request by vsevel**

### CODE REVIEW

**Comment by kdubb** [comment]
@vsevel 4.1.0.CR1 passed after I reran the action. I had the same issue yesterday on another extension.

**Comment by kdubb** [comment]
It looks like you attempted a 3rd run, which failed because the version was already released.

**Comment by kdubb** [comment]
Apologies... should have given you the heads up. Gastaldi asked me to check if it was working again and I though I'd try more than just the one other extension.

**Comment by vsevel** [comment]
no problem. as long as this is done and successful.

**Pull request closed without merging**
