### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by vsevel**
cc @gsmet @kdubb

### CODE REVIEW

**Comment by kdubb** [comment]
Is there test coverage for failure we are working around in Quarkus main?

**Review by geoand — APPROVED** [review]

**Comment by vsevel** [comment]
must have missed again something it did not create the tag 
@gastaldi are you available to help?

**Comment by gsmet** [comment]
@vsevel there was a test failure during the release:
```
 Error: [ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.763 s <<< FAILURE! -- in io.quarkus.vault.VaultTransitITCase
Error: [ERROR] io.quarkus.vault.VaultTransitITCase.keyVersionSignBatch -- Time elapsed: 0.029 s <<< FAILURE!
[INFO] org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
[INFO] 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[INFO] 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[INFO] 	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
[INFO] 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
[INFO] 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
[INFO] 	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
[INFO] 	at io.quarkus.vault.VaultTransitITCase.keyVersionSignBatch(VaultTransitITCase.java:295)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO] 	at io.quarkus.test.QuarkusUnitTest.runExtensionMethod(QuarkusUnitTest.java:499)
[INFO] 	at io.quarkus.test.QuarkusUnitTest.interceptTestMethod(QuarkusUnitTest.java:413)
```

**Comment by vsevel** [comment]
I am going to try again

**Pull request merged**
