### PR TITLE
quarkiverse-parent 15

### PR DESCRIPTION
**Pull request by vsevel**
needed to rename field `sealed` because of error generated in `impsort`: `(line 11,col 12) Parse error. Found "sealed", expected one of  "enum" "exports" "module" "open" "opens" "provides" "record" "requires" "strictfp" "to" "transitive" "uses" "with" "yield" <IDENTIFIER>
`

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by kdubb** [comment]
@gastaldi Any ideas on this?

**Comment by gastaldi** [comment]
Confirmed. It's a bug in the javaparser. Using a newer dependency fixes the problem:
```xml
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>com.github.javaparser</groupId>
                        <artifactId>javaparser-core</artifactId>
                        <version>3.25.4</version>
                    </dependency>
                </dependencies>
            </plugin>

```

**Comment by gastaldi** [comment]
Pull-request created: https://github.com/revelc/impsort-maven-plugin/pull/74

**Comment by kdubb** [comment]
Ok. I'm good with it; just seemed like this was a parser issue and not something we should deal with.

Given the long trail from "JavaParser" -> "Vault Extension", seems like a rename might be in order if this update is important.

**Pull request merged**
